//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_Table
    {
        public int r_Id { get; set; }
        public Nullable<int> poll_Id { get; set; }
        public string location_Name { get; set; }
        public string mandatory_Calls { get; set; }
        public string status_Old { get; set; }
        public string status_New { get; set; }
        public string user_Name { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> change_Date { get; set; }
    }
}
