//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_zones
    {
        public int id_zone { get; set; }
        public Nullable<int> zone { get; set; }
        public string zone_Name { get; set; }
        public string zone_Kml { get; set; }
        public Nullable<int> zone_Active { get; set; }
    }
}
