//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_poll_ContactDetails
    {
        public int r_Id { get; set; }
        public int poll_Id { get; set; }
        public string contact_FirstName { get; set; }
        public string contact_LastName { get; set; }
        public string contact_Type { get; set; }
        public string contact_Info { get; set; }
    }
}
