//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class election_Precinct
    {
        public int poll_Id { get; set; }
        public int precinct_Id { get; set; }
        public string ward_Name { get; set; }
        public string precinct { get; set; }
    }
}
