//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionReportingEntities : DbContext
    {
        public ElectionReportingEntities()
            : base("name=ElectionReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<election_Precinct> election_Precinct { get; set; }
        public virtual DbSet<poll_Location> poll_Location { get; set; }
        public virtual DbSet<poll_Location_All> poll_Location_All { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<dbo_zones> dbo_zones { get; set; }
        public virtual DbSet<dbo_poll_ContactDetails> dbo_poll_ContactDetails { get; set; }
        public virtual DbSet<LocTrackMain> LocTrackMains { get; set; }
        public virtual DbSet<audit_Table> audit_Table { get; set; }
    }
}
